---
- name: 1-3 Check https port 443 is enabled 
  hosts: all
  tags: paw_check_1-3

  tasks:

  - name: Status of https port 443 in firewalld daemon
    ansible.builtin.command:
      cmd: firewall-cmd --list-ports
    register: https_result
    changed_when: false
    
  - name: Display status of https port 443
    ansible.builtin.debug:  
      msg: Result is {{ https_result.stdout_lines }}

  - name: Check if https port 443 is enabled in firewalld daemon
    ansible.builtin.assert:
      that:
        - "'443' in https_result.stdout"
      fail_msg: "Non-Compliance! Https port 443  is not enabled in firewalld daemon"
      success_msg: "Compliance! Https port 443  is enabled in firewalld daemon"
#      quiet: true

    register: result
    changed_when:
      - result.evaluated_to is defined
      - result.evaluated_to == false
    failed_when: false
