---
- name: 1-1 Check memory allocation
  hosts: all
  tags: paw_check_1-1

  tasks:
  - name: Display variables measured
    ansible.builtin.debug:
      msg: Result is {{ ansible_memtotal_mb }}

  - name: check if memory allocated is between 800 and 2000 MB
    ansible.builtin.assert:
      that:
        - ansible_memtotal_mb | int >= 800
        - ansible_memtotal_mb | int <= 2000
      fail_msg: "Non-compliance! Memory is {{ ansible_memtotal_mb }} MB"
      success_msg: "Compliance!"
    register: result
    changed_when:
      - result.evaluated_to is defined
      - result.evaluated_to == False
    failed_when: False
